/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;

import jdk.internal.vm.Continuation;
import jdk.internal.vm.ContinuationScope;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
